### ISSUE TITLE
Dark mode in chrome makes it hard to see time

### ISSUE THREAD

**Issue by karmatosed** [folletto/Blipread#5]
In dark mode I see the following:

![image](https://user-images.githubusercontent.com/253067/70330808-31bd1f80-1836-11ea-923d-708c27712b10.png)

**Comment by folletto** [comment]
Ach yes, the black text is hardcoded and I didn't think dark mode was not a good match.

And unfortunately, it seems Chrome doesn't provide an easy way in JS to detect it, but there seem to be a workaround:
https://stackoverflow.com/questions/58880234/toggle-chrome-extension-icon-based-on-light-or-dark-mode-browser

**Comment by folletto** [comment]
Submitted 1.0.2 to Chrome Store for review.
Unfortunately it seems they want to review the extension and this will take "several weeks" due to the extension having full access to the page. Disappointing. :|

**Comment by folletto** [comment]
1.0.2 is live.
