### ISSUE TITLE
Browser icon number is hard to read on dark themed browsers

### ISSUE THREAD

**Issue by goleary** [folletto/Blipread#7]
Awesome extension!

![image](https://user-images.githubusercontent.com/16123225/127537863-42a8ec7b-1afa-44f8-9e25-f6aadc451f2d.png)

**Comment by folletto** [comment]
Hey, thanks!

And thanks for the report, I need to look into how I can detect the changed color and reverse the text.

**Comment by goleary** [comment]
What might be even easier is to have a light background in the SVG which wouldn't really be noticeable with a light theme but would enable reading the number on a dark theme.

**Comment by folletto** [comment]
I did some digging. As I checked, I also recalled I did use a check for that... 
https://github.com/folletto/Blipread/blob/ca3e8b482ab189c2b0c360c3ee5cf8c8a88779ff/js/background.js#L65

...not quite. The above checks for a system dark theme, not for the theme color.

So it seems this issue shows up in the situation where the system color is light AND the theme color is dark. 

Which means I've to find a different approach... ^^'

**Comment by folletto** [comment]
I've asked here:
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/vq4F0YtmA5U

**Comment by folletto** [comment]
Given there's no way to automatically detect, I've added an option in settings to change the color manually. Annoying workaround, but at least there's a workaround. ;)

The extension is currently pending review, should go up as v1.0.3 as soon as they verify it.

**Comment by goleary** [comment]
cool, thanks for the workaround!
